filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"
- add_host_metadata:
    when.not.contains.tags: forwarded

output.elasticsearch:
  hosts: ["<ELASTIC_HOST>"]
  protocol: "https"
  api_key: "${ELASTICSEARCH_API_KEY}"
  ssl.verification_mode: certificate
  index: "docker-logs"

setup.template.enabled: false
setup.ilm.enabled: true

logging.level: info
